### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by AndreaGiardini**
This pull requests adds a working Dockerfile to the project

On top of that, it would be nice to automate the building/publishing of Docker images to hub.docker.com, introducing version numbers.

### CODE REVIEW

**Comment by matriv** [comment]
@AndreaGiardini 
You could also add the line to expose port `9268` to ease the mapping of it on a running container.

**Comment by AndreaGiardini** [comment]
@matriv Fixed! would be nice to have it pushed automatically to https://hub.docker.com/r/crate/

**Comment by matriv** [comment]
@AndreaGiardini Thanks again. I forgot to tell you earlier but please follow the instructions bellow and sign our CLA so that we proceed and merge your PR.
https://crate.io/community/contribute/agreements/

**Comment by matriv** [comment]
@AndreaGiardini Added to docker hub: https://hub.docker.com/r/crate/crate_adapter/
Thanks for your contribution!

**Comment by AndreaGiardini** [comment]
Thanks, would be nice to have tags for different versions as well

**Comment by matriv** [comment]
You think it's already necessary? Not enough to build new image from master every time as latest?
We don't have any branches/tags here yet

**Pull request merged**
